name: continuous integration

on: push

jobs:
  continuous_integration:
    runs-on: ubuntu-latest

    steps:
      - name: Clonagem projeto
        uses: actions/checkout@v3
      
      - name: Configuração Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
